### ISSUE TITLE
你这5000兆元有问题啊（

### ISSUE THREAD

**Issue by jcjrobert** [MeetWq/nonebot-plugin-logo#2]
如图所示
![QQ图片20220217135919](https://user-images.githubusercontent.com/52129454/154415072-42bc4d7f-be2d-45fc-9a17-4d6ce7686e35.png)

**Comment by MeetWq** [comment]
应该是字体问题，但暂时不知道怎么解决，在本地生成是正常的

**Comment by jcjrobert** [comment]
确实是字体问题，换成思源黑体就正常了

**Comment by jcjrobert** [comment]
好像并不是字体问题，因为换了还是有
![O}IYC%A)KL9HYDL1O 8KLYP](https://user-images.githubusercontent.com/52129454/158734776-9c4ff530-4571-49e1-a2bc-6edaf14e8c21.PNG)
